services:
  - type: web
    name: fastapi-hackrx
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: MISTRAL_API_KEY
        value: tpsvvZJrPHhX7VEfRwfu7wwldOnrovtp
      - key: API_TOKEN
        value: 116e40aae54b8871e74fad8274c54ce0caa00fcf67446c5d280794506114f42f
